package(default_visibility = ["//visibility:public"])

exports_files(["mxe"])

py_binary(
    name = "downloader",
    srcs = ["downloader.py"],
)

py_binary(
    name = "zip4win",
    srcs = ["zip4win.py"],
)
